name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          ssh-keyscan "${{ secrets.HOST }}" >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          ssh root@"${{ secrets.HOST }}" whoami

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run Nixos Rebuild
        run: nix-shell -p nixos-rebuild --run "nixos-rebuild switch --flake . --target-host root@${{ secrets.HOST }}"
